<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
$buildJsFile = 'Esparksinc_IvyPaymentHyvaCompatibility::js/react-checkout.js';
?>
<script>
    function loadReactCartScript () {
        const scriptTag = 'script';
        const firstScript = document.getElementsByTagName(scriptTag)[0];
        const newScript = document.createElement(scriptTag);

        newScript.async = true;
        newScript.defer = true;
        newScript.src = '<?= $escaper->escapeUrl($block->getViewFileUrl($buildJsFile)); ?>';

        firstScript.parentNode.insertBefore(newScript, firstScript);
    }
    window.addEventListener("private-content-loaded", loadReactCartScript);
</script>
