<?php $_product = $block->getProduct(); ?>
<?php $banner = $block->getBannerData(); ?>

<button
    class="ivy-checkout-button ivy-product-button"
    data-cart-value="<?= $_product->getFinalPrice() ?>"
    data-shop-category="<?= $banner->getMcc() ?>"
    data-currency-code="<?= $_product->getStore()->getCurrentCurrencyCode(); ?>"
    data-locale="<?= $banner->getLocale() ?>"
    style="visibility: hidden; display:none">
</button>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        let button = document.querySelector('.ivy-product-button');

        button.addEventListener('click', (event) => {
            event.preventDefault();

            let form = document.getElementById('product_addtocart_form');
            let body = document.querySelector('body');

            if (form.checkValidity()) {
                form.submit();
                //body.trigger('processStart'); //loading start...
                setTimeout(function () {
                    let linkUrl = window.BASE_URL + "ivypayment/checkout/index/express/1";

                    fetch(linkUrl, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-Requested-With': 'XMLHttpRequest'
                        },
                    }).then((response) => response.json())
                        .then((result) => {
                            //body.trigger('processStop'); //loading stop...
                            window.startIvyCheckout(result.redirectUrl, 'popup');
                        })
                        .catch((error) => {
                            //body.trigger('processStop'); //loading stop...
                            dispatchMessages([
                                {
                                    type: "error",
                                    text: error
                                }
                            ]);
                        });
                }, 3000);
            }
        });
        setTimeout(function () {
            button.style.display = 'block';
        }, 3000);
    });
</script>
