<?php $_product = $block->getProduct(); ?>
<?php $banner = $block->getBannerData(); ?>

<button
    class="ivy-checkout-button ivy-product-button"
    data-cart-value="<?= $_product->getFinalPrice() ?>"
    data-shop-category="<?= $banner->getMcc() ?>"
    data-currency-code="<?= $_product->getStore()->getCurrentCurrencyCode(); ?>"
    data-locale="<?= $banner->getLocale() ?>"
    style="visibility: hidden; display:none">
</button>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        let button = document.querySelector('.ivy-product-button');

        button.addEventListener('click', (event) => {
            event.preventDefault();

            let form = document.getElementById('product_addtocart_form');
            let body = document.querySelector('.ivy-product-button');

            if (form.checkValidity()) {
                form.submit();
                setTimeout(function () {
                    let linkUrl = window.BASE_URL + "ivypayment/checkout/index/express/1";

                    fetch(linkUrl, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-Requested-With': 'XMLHttpRequest'
                        },
                    }).then((response) => response.json())
                        .then((result) => {
                            window.startIvyCheckout(result.redirectUrl, 'popup');
                        })
                        .catch((error) => {
                            dispatchMessages([
                                {
                                    type: "error",
                                    text: error
                                }
                            ]);
                        });
                }, 3000);
            }
        });
        setTimeout(function () {
            button.style.display = 'block';
        }, 3000);
    });
</script>

<!--<script>-->
<!--    require(['jquery', 'mage/url', 'Magento_Ui/js/model/messageList', 'domReady!'], function ($, url, messageList) {-->
<!--        $(".ivy-product-button").on('click', function (event) {-->
<!--            event.preventDefault();-->
<!--            if ($('#product_addtocart_form').valid()) {-->
<!--                $('#product_addtocart_form').submit();-->
<!--                $("body").trigger('processStart');-->
<!--                setTimeout(function () {-->
<!--                    var linkUrl = url.build('ivypayment/checkout/index/express/1');-->
<!--                    $.ajax({-->
<!--                        url: linkUrl,-->
<!--                        type: 'POST',-->
<!--                        success: function (response) {-->
<!--                            $("body").trigger('processStop');-->
<!--                            window.startIvyCheckout(response.redirectUrl, 'popup')-->
<!--                        },-->
<!--                        error: function (xhr, status, errorThrown) {-->
<!--                            $("body").trigger('processStop');-->
<!--                            messageList.addErrorMessage({message: errorThrown});-->
<!--                        }-->
<!--                    });-->
<!--                }, 3000);-->
<!--            }-->
<!--        });-->
<!--        setTimeout(function () {-->
<!--            $('.ivy-product-button').show();-->
<!--        }, 3000);-->
<!--    });-->
<!---->
<!--</script>-->
